# このファイルをpushしたらこのファイルのGithubアクションが実行される
name: test
on:
  push:
    paths:
      - .github/workflows/test.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu:20.04
          - ubuntu:22.04
          - debian:10
          - debian:11
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          docker system df
          docker build . --file Dockerfile --platform linux/amd64 --tag test-container --build-arg DOCKER_IMAGE_NAME=${{ matrix.image }}
          docker image ls
          # docker container run test-container --mount type=bind,source=${{ github.workspace }},target=/home/user "ls"
          docker compose run -e DOCKER_IMAGE_NAME=${{ matrix.image }} web
          docker ps -a